defmodule Ash2186.Repo.Migrations.AddResources do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:resource_b, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true)
      add(:state, :smallint, null: false, default: 0)
    end

    create table(:resource_a, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true)
      add(:locale_preference, :map)
    end
  end

  def down do
    drop(table(:resource_a))

    drop(table(:resource_b))
  end
end
